### ISSUE TITLE
Multiple issues and agreements for book-keeping

### ISSUE THREAD

**Issue by jayanthjaiswal** [cdli-gh/atf2conll-convertor#6]
https://github.com/jayanthjaiswal/Convertor/issues/1

**Comment by epageperron** [comment]
I went through the checker errors you gave me, please see the Slack thread under the out.txt file you send. The checker rules should match the ID creation rules so it should be helpful? Also here is the file where we have the ATF structure draft https://docs.google.com/document/d/14aHO-rvcSdTDY-ULmY_bXB5PYrZxGz5WMfYzF2VmWTI/edit   . Maybe you can start a graph based on it?

**Comment by khoidt** [comment]
## Line format breaks when no whitespace between dot after line number and first sign

You are probably aware of this problem, and this is in fact an ATF formatting mistake. However, as the issue seems pretty common, perhaps it would make sense to implement an automatic fix while converting.

**Examples:**
**Text:** P102287
ATF line:  `21.1(asz) 1(ban2) gur kiszib3 ga-a-me`
CoNNL lines:
```
r.21.1(asz).1	1(ban2)	_	_	_	_	_
r.21.1(asz).2	gur	_	_	_	_	_
r.21.1(asz).3	kiszib3	_	_	_	_	_
r.21.1(asz).4	ga-a-me	_	_	_	_	_
```

ATF line:  
`23.szunigin 2(gesz'u) 2(gesz2) 4(u) 3(asz) 4(barig) 4(ban2) 1(disz) 1/2(disz) sila3 sze gur`
CoNNL lines:
```
r.23.szunigin.1	2(gesz'u)	_	_	_	_	_
r.23.szunigin.2	2(gesz2)	_	_	_	_	_
r.23.szunigin.3	4(u)	_	_	_	_	_
r.23.szunigin.4	3(asz)	_	_	_	_	_
r.23.szunigin.5	4(barig)	_	_	_	_	_
r.23.szunigin.6	4(ban2)	_	_	_	_	_
r.23.szunigin.7	1(disz)	_	_	_	_	_
r.23.szunigin.8	1/2(disz)	_	_	_	_	_
r.23.szunigin.9	sila3	_	_	_	_	_
r.23.szunigin.10	sze	_	_	_	_	_
r.23.szunigin.11	gur	_	_	_	_	_
```
**Morphological preannotator error message:**
`Error: The id s003649.2.1 in line number 16 in file CoNLL\P114280.conll does not follow the Conll format "^e?(o|r|t|b|l|ri|(s?[a-z]?[0-9]?))\.(col[0-9]'?\.)?[0-9]+'?\.[0-9]+$".`

**Comment by khoidt** [comment]
## Adding empty placeholders (_)
To my understanding, empty placeholders for SEGM, XPOSTAG, HEAD, DEPREL, and MISC are required by the Morphological pre-annotator, but are not produced in the CoNLL files during conversion. I have a separate script that adds them, but I think it would make sense to add such an option to the CoNLL2ATF converter itself.

**Comment by epageperron** [comment]
I am not sure why the pre-annotator wasn't running properly but it doesn't require the underscores, it just warns that they aren't there.  

We did have discussions on adding functions to clean the annotations after the editor has done their work, in particular deleting extra data in other columns and adding the underscores but I don't know it if has been implemented, I don't think so

**Comment by epageperron** [comment]
About the problem when no white space, normally there is always a white space and that is something that should be covered by the ATF checker. The ATF checker could be invoked by the ATF2Conll converter

**Comment by jayanthjaiswal** [comment]
@epageperron @khoidt I have integrated the atf checker (pyoracc) with this tool. So, it will give an error on the atf. Is there anything else to be done here or is this some issue with the pre-annotator tool?

**Comment by jayanthjaiswal** [comment]
@epageperron if this tool is ok, please close this and create issues in other tools, if they require any change.

**Comment by epageperron** [comment]
Yes ok let's follow up on issues in the correct tool issues feed
